import { createRequire } from 'module';
import { execSync } from 'child_process';
import { serve } from '../tests/serve.mjs';
const require = createRequire(import.meta.url);
function pw(){const c=[process.env.PLAYWRIGHT_PATH];try{c.push(execSync('npm root -g',{encoding:'utf8'}).trim()+'/playwright');}catch{}c.push('playwright');for(const x of c){if(!x)continue;try{return require(x);}catch{}}throw new Error('no pw');}
const { chromium } = pw();
const srv = await serve();
const browser = await chromium.launch();
const page = await browser.newPage({ viewport:{width:1620,height:460}, deviceScaleFactor:2 });
page.on('pageerror', e=>console.error('PAGEERR', String(e)));
await page.goto(srv.url + '/tools/_scratch_view.html');
await page.waitForFunction(()=>window.__ready,{timeout:15000});
const key = process.argv[2]||'azure';
const tier = Number(process.argv[3]??2);
const pose = process.argv[4]||'glide';
await page.evaluate(([k,t,p])=>window.render(k,t,p),[key,tier,pose]);
await page.waitForTimeout(150);
await (await page.$('#montage')).screenshot({ path:`/tmp/view-${key}-t${tier}-${pose}.png` });
console.log(`wrote /tmp/view-${key}-t${tier}-${pose}.png`);
await browser.close(); srv.close();
