import { createRequire } from 'module';
import { execSync } from 'child_process';
import { serve } from '../tests/serve.mjs';
const require = createRequire(import.meta.url);
const pw = (() => { for (const x of [process.env.PLAYWRIGHT_PATH, execSync('npm root -g',{encoding:'utf8'}).trim()+'/playwright','playwright']) { try { return require(x); } catch {} } throw new Error('no pw'); })();
const srv = await serve();
const browser = await pw.chromium.launch();
const page = await browser.newPage();
const logs = [];
page.on('console', m => logs.push(m.text()));
page.on('pageerror', e => logs.push('PAGEERROR '+e));
await page.goto(srv.url + '/tools/celestial3D.html');
await page.waitForFunction(() => window.__ready, { timeout: 20000 });
// isolate the spine: turn off plates + seams + struts so ONLY the diamonds (and body/wings) show
await page.evaluate(() => { for (const id of ['bPlates','bSeams','bStruts']) { const b=document.getElementById(id); if (b.classList.contains('on')) b.click(); } });
await page.evaluate(() => window.__view(0, 0.18, false));
await page.evaluate(() => window.__zoom(0.45));
await page.waitForTimeout(200);
await page.screenshot({ path: '/tmp/c3d-spine-only.png' });
console.log('CONSOLE:', logs.filter(l => /spine|PAGEERROR/.test(l)).join('\n'));
console.log('wrote /tmp/c3d-spine-only.png');
await browser.close(); await srv.close(); process.exit(0);
